#define MAX_ACK_TIME_IN_S 1
#define TIMER_TICK_INTERVALL_MS 1000
#define MAX_MESSAGE_TIMEOUT_COUNT 15
#define MAX_PING_MESSAGE_TIMEOUT_COUNT 3

#define CLIENT_MESSAGE_DROP_CHANCE 0 // Between 0 and 100

#define MAX_CONTENT_LENGTH 1000
#define MAX_HASH_PART_SIZE_BYTE 16777216